export const FETCH_HOME_DATA_REQUEST = 'FETCH_HOME_DATA_REQUEST';
export const FETCH_HOME_DATA_SUCCESS = 'FETCH_HOME_DATA_SUCCESS';
export const FETCH_HOME_DATA_FAILURE = 'FETCH_HOME_DATA_FAILURE';

export const SEND_CONTACT_FORM_REQUEST = 'SEND_CONTACT_FORM_REQUEST';
export const SEND_CONTACT_FORM_SUCCESS = 'SEND_CONTACT_FORM_SUCCESS';
export const SEND_CONTACT_FORM_FAILURE = 'SEND_CONTACT_FORM_FAILURE';

export const FETCH_BANNER_DATA_REQUEST = 'FETCH_BANNER_DATA_REQUEST';
export const FETCH_BANNER_DATA_SUCCESS = 'FETCH_BANNER_DATA_SUCCESS';
export const FETCH_BANNER_DATA_FAILURE = 'FETCH_BANNER_DATA_FAILURE';

export const FETCH_HEADER_DATA_REQUEST = 'FETCH_HEADER_DATA_REQUEST';
export const FETCH_HEADER_DATA_SUCCESS = 'FETCH_HEADER_DATA_SUCCESS';
export const FETCH_HEADER_DATA_FAILURE = 'FETCH_HEADER_DATA_FAILURE';
