export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// Film-related action types
export const FETCH_FILMS_REQUEST = 'FETCH_FILMS_REQUEST';
export const FETCH_FILMS_SUCCESS = 'FETCH_FILMS_SUCCESS';
export const FETCH_FILMS_FAILURE = 'FETCH_FILMS_FAILURE';

export const POST_FILM_REQUEST = 'POST_FILM_REQUEST';
export const POST_FILM_SUCCESS = 'POST_FILM_SUCCESS';
export const POST_FILM_FAILURE = 'POST_FILM_FAILURE';

export const PATCH_FILM_REQUEST = 'PATCH_FILM_REQUEST';
export const PATCH_FILM_SUCCESS = 'PATCH_FILM_SUCCESS';
export const PATCH_FILM_FAILURE = 'PATCH_FILM_FAILURE';

export const FETCH_COUNTRIES_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAILURE = 'FETCH_COUNTRIES_FAILURE';

export const FETCH_LANGUAGE_REQUEST = 'FETCH_COUNTRIES_REQUEST';
export const FETCH_LANGUAGE_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_LANGUAGE_FAILURE = 'FETCH_COUNTRIES_FAILURE';

